### ISSUE TITLE
Error: No CORS Headers

### ISSUE THREAD

**Issue by jodelajo** [abczzz13/fndr_backend#1]
Hi Thomas!
While implementing the live-backend-API I ran into an error:

> "Access to XMLHttpRequest at 'https://fndr-backend-production.herokuapp.com/api/v1/companies' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

<img width="1349" alt="Schermafbeelding 2022-03-02 om 15 57 42" src="https://user-images.githubusercontent.com/74967270/156388095-2924e30a-ddfd-4ad4-8bb0-9d5fa58e92ff.png">

Here is more information over [CORS header 'Access-Control-Allow-Origin' missing](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)

> "What went wrong?
> 
> The response to the [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS) request is missing the required [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header, which is used to determine whether or not the resource can be accessed by content operating within the current origin."

This package [Flask-CORS](https://github.com/corydolphin/flask-cors) might be the answer to this problem.

Please, take a look at this error, because now I'm stuck (*tuning in on netflix 😬📺*).

**Comment by abczzz13** [comment]
Will start working on this immediately. I'll keep you posted!
