### ISSUE TITLE
Feature request: /check_token endpoint

### ISSUE THREAD

**Issue by jodelajo** [abczzz13/fndr_backend#11]
## What & Why
It would be nice to have a /check_token endpoint that allows us to check if a token is still valid when the app loads. In addition it would be nice if it sends back the username so we can display it in the navbar.

## Anything else

- We can send the token as an authorization header (like with the other endpoints).

**Comment by abczzz13** [comment]
Good suggestion!

Don't see any problems implementing this feature. Hope to to implement it later today.
